import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f1f5f9',
    },
    header: {
        marginTop: 16,
        paddingHorizontal: 20,
        paddingTop: 8,
        paddingBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    headerTitle: {
        flex: 1,
        marginLeft: 12,
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 32,
        paddingTop: 8,
    },
    statusCard: {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.04,
        shadowRadius: 16,
        elevation: 3,
    },
    statusHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    statusBadge: {
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 999,
    },
    statusBadgeActive: {
        backgroundColor: '#dcfce7',
    },
    statusBadgeClosed: {
        backgroundColor: '#e0f2fe',
    },
    statusBadgeCancelled: {
        backgroundColor: '#fee2e2',
    },
    statusBadgeText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#0f172a',
    },
    statusCountdown: {
        fontSize: 28,
        fontWeight: '700',
        color: '#0f172a',
    },
    statusCountdownMuted: {
        color: '#94a3b8',
    },
    statusDescription: {
        marginTop: 12,
        fontSize: 15,
        color: '#111827',
        lineHeight: 22,
    },
    statusHint: {
        marginTop: 6,
        fontSize: 13,
        color: '#64748b',
        lineHeight: 18,
    },
    statusFooterRow: {
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    statusFooterText: {
        marginLeft: 8,
        fontSize: 13,
        color: '#1f2937',
    },
    section: {
        marginTop: 24,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sectionTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: '#0f172a',
    },
    sectionBadge: {
        marginLeft: 8,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: '#e0f2fe',
    },
    sectionBadgeText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#0369a1',
    },
    sectionSubtitle: {
        marginTop: 8,
        fontSize: 13,
        color: '#64748b',
        lineHeight: 18,
    },
    requestDescription: {
        marginTop: 12,
        fontSize: 14,
        color: '#1f2937',
        lineHeight: 20,
    },
    requestMetaRow: {
        marginTop: 12,
        flexDirection: 'row',
        alignItems: 'center',
    },
    requestMetaIcon: {
        marginRight: 6,
    },
    requestMetaText: {
        flex: 1,
        fontSize: 13,
        color: '#0369a1',
    },
    attachmentsScroll: {
        paddingVertical: 6,
    },
    attachmentImage: {
        width: 120,
        height: 120,
        borderRadius: 12,
        marginRight: 12,
        backgroundColor: '#e2e8f0',
    },
    proposalsList: {
        marginTop: 16,
    },
    proposalsCardsWrapper: {
        width: '100%',
    },
    proposalCard: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#dbeafe',
        backgroundColor: '#f8fbff',
        padding: 16,
        marginBottom: 12,
    },
    proposalCardWinner: {
        borderColor: '#facc15',
        backgroundColor: '#fefce8',
    },
    proposalCardSelected: {
        borderColor: '#0f766e',
        backgroundColor: '#ecfdf5',
    },
    proposalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    proposalProvider: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0f172a',
        flexShrink: 1,
        paddingRight: 6,
    },
    proposalPrice: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0f172a',
    },
    proposalMetaRow: {
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    proposalMetaText: {
        marginLeft: 8,
        fontSize: 13,
        color: '#475569',
        flex: 1,
        lineHeight: 18,
    },
    proposalNotes: {
        marginTop: 10,
        fontSize: 13,
        color: '#1f2937',
        lineHeight: 18,
    },
    proposalFooterRow: {
        marginTop: 14,
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    proposalSelectButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#cbd5f5',
        backgroundColor: '#ffffff',
        paddingHorizontal: 14,
        paddingVertical: 8,
    },
    proposalSelectButtonActive: {
        borderColor: '#0f766e',
        backgroundColor: '#d1fae5',
    },
    proposalSelectButtonLabel: {
        marginLeft: 8,
        fontSize: 13,
        fontWeight: '600',
        color: '#475569',
    },
    proposalSelectButtonLabelActive: {
        color: '#0f766e',
    },
    proposalsControlsRow: {
        marginTop: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    proposalsControlsLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#1f2937',
    },
    proposalsFiltersRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: -8,
        paddingLeft: 8,
    },
    proposalsFilterChip: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: '#cbd5f5',
        backgroundColor: '#ffffff',
        marginLeft: 8,
    },
    proposalsFilterChipActive: {
        borderColor: '#0ea5e9',
        backgroundColor: '#e0f2fe',
    },
    proposalsFilterChipText: {
        marginLeft: 6,
        fontSize: 13,
        fontWeight: '600',
        color: '#475569',
    },
    proposalsFilterChipTextActive: {
        color: '#0f172a',
    },
    proposalScrollContainer: {
        maxHeight: 336,
    },
    proposalScrollContent: {
        paddingBottom: 4,
    },
    emptyOffersBox: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        padding: 24,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f8fafc',
    },
    emptyOffersText: {
        marginTop: 12,
        fontSize: 14,
        color: '#475569',
        textAlign: 'center',
        lineHeight: 20,
    },
    winnerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    winnerHeaderText: {
        marginLeft: 8,
        fontSize: 15,
        fontWeight: '700',
        color: '#b45309',
        flex: 1,
    },
    winnerCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 20,
        padding: 18,
        borderWidth: 1,
        borderColor: '#dbeafe',
    },
    winnerAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginRight: 16,
    },
    winnerAvatarFallback: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginRight: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#e2e8f0',
    },
    winnerInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    winnerName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    winnerReputationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
    },
    winnerReputationText: {
        marginLeft: 6,
        fontSize: 14,
        fontWeight: '600',
        color: '#0f172a',
    },
    winnerReviewsText: {
        marginLeft: 4,
        fontSize: 13,
        color: '#64748b',
    },
    winnerDetailCard: {
        marginTop: 16,
        backgroundColor: '#ecfeff',
        borderRadius: 18,
        padding: 18,
        borderWidth: 1,
        borderColor: '#bae6fd',
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
    },
    detailValue: {
        marginLeft: 8,
        fontSize: 14,
        color: '#0f172a',
        flex: 1,
        lineHeight: 20,
    },
    detailNotesBox: {
        marginTop: 16,
        backgroundColor: '#f8fafc',
        borderRadius: 14,
        padding: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    detailNotesTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: '#0f172a',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 6,
    },
    detailNotesText: {
        fontSize: 14,
        color: '#1f2937',
        lineHeight: 20,
    },
    actionsContainer: {
        marginTop: 24,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    selectedProposalCaption: {
        marginTop: 8,
        fontSize: 13,
        color: '#0f172a',
        textAlign: 'center',
    },
    selectedProposalHelper: {
        marginTop: 8,
        fontSize: 13,
        color: '#64748b',
        textAlign: 'center',
    },
    payButton: {
        borderRadius: 16,
        paddingVertical: 16,
        paddingHorizontal: 20,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: '#0f766e',
        marginTop: 16,
        marginBottom: 12,
    },
    payButtonDisabled: {
        backgroundColor: '#d1fae5',
        borderWidth: 1,
        borderColor: '#0f766e',
    },
    payButtonIcon: {
        marginRight: 8,
    },
    payButtonText: {
        color: '#ecfeff',
        fontSize: 16,
        fontWeight: '700',
    },
    payButtonTextDisabled: {
        color: '#047857',
    },
    closeButton: {
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        backgroundColor: '#0f766e',
        marginBottom: 12,
    },
    closeButtonDisabled: {
        backgroundColor: '#94a3b8',
    },
    closeButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '700',
    },
    closeButtonTextDisabled: {
        color: '#e2e8f0',
    },
    closeHelperText: {
        marginTop: 6,
        fontSize: 13,
        color: '#f0fdfa',
        textAlign: 'center',
    },
    cancelButton: {
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: '#ef4444',
        paddingVertical: 14,
        alignItems: 'center',
        backgroundColor: '#fff5f5',
    },
    cancelButtonText: {
        color: '#b91c1c',
        fontSize: 16,
        fontWeight: '700',
    },
    cancelButtonTextDisabled: {
        color: '#fca5a5',
    },
    buttonDisabled: {
        opacity: 0.6,
    },
    serviceConfirmedNote: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ecfdf5',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginBottom: 12,
    },
    serviceConfirmedNoteIcon: {
        marginRight: 8,
    },
    serviceConfirmedNoteText: {
        flex: 1,
        fontSize: 13,
        lineHeight: 18,
        color: '#0f766e',
    },
    helperCaption: {
        marginTop: 12,
        fontSize: 13,
        color: '#64748b',
        textAlign: 'center',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        justifyContent: 'flex-start',
    },
    modalContainer: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: 32,
        flex: 1,
        maxHeight: '92%',
        alignSelf: 'stretch',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 20,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderColor: '#e5e7eb',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
    },
    modalCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f3f4f6',
    },
    modalContent: {
        paddingHorizontal: 24,
        paddingVertical: 18,
        paddingBottom: 40,
    },
    modalSection: {
        marginBottom: 18,
    },
    modalLabel: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        color: '#6b7280',
        letterSpacing: 0.6,
        marginBottom: 4,
    },
    modalValue: {
        fontSize: 15,
        lineHeight: 21,
        color: '#1f2937',
    },
    modalProviderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalProviderAvatar: {
        width: 64,
        height: 64,
        borderRadius: 32,
        marginRight: 16,
    },
    modalProviderAvatarFallback: {
        width: 64,
        height: 64,
        borderRadius: 32,
        marginRight: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#e2e8f0',
    },
    modalProviderInfo: {
        flex: 1,
    },
    modalProviderName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    modalProviderMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
    },
    modalProviderMetaText: {
        marginLeft: 6,
        fontSize: 13,
        color: '#475569',
    },
    modalNotesBox: {
        marginTop: 8,
        backgroundColor: '#f8fafc',
        borderRadius: 14,
        padding: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    modalNotesLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#0f172a',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 6,
    },
    modalNotesText: {
        fontSize: 14,
        color: '#1f2937',
        lineHeight: 20,
    },
    modalEmptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 32,
    },
    modalEmptyStateText: {
        marginTop: 12,
        fontSize: 14,
        color: '#64748b',
        textAlign: 'center',
        lineHeight: 20,
    },
});

export default styles;
