import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        marginTop: 16,
        paddingHorizontal: 20,
        paddingTop: 8,
        paddingBottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    infoButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: '#e0f2fe',
        borderRadius: 16,
    },
    infoButtonText: {
        marginLeft: 6,
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
    },
    statusWrapper: {
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 16,
        alignItems: 'center',
    },
    brandLogo: {
        width: 96,
        height: 96,
        marginBottom: 12,
    },
    statusTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 8,
        textAlign: 'center',
    },
    timerLabel: {
        fontSize: 13,
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    timerValue: {
        marginTop: 4,
        fontSize: 34,
        fontWeight: '700',
        color: '#0f172a',
    },
    timerValueClosed: {
        color: '#9ca3af',
    },
    statusSubtitle: {
        marginTop: 8,
        fontSize: 15,
        color: '#6b7280',
        textAlign: 'center',
    },
    infoPill: {
        marginTop: 12,
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#ecfdf5',
        borderRadius: 999,
    },
    infoPillText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#047857',
        textAlign: 'center',
    },
    offerBadge: {
        marginTop: 12,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e0f2fe',
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 999,
    },
    offerBadgeText: {
        marginLeft: 8,
        fontSize: 13,
        fontWeight: '600',
        color: '#0369a1',
    },
    listContent: {
        paddingHorizontal: 18,
        paddingVertical: 20,
        paddingBottom: 32,
    },
    offerCard: {
        backgroundColor: '#f0f5f2',
        borderRadius: 18,
        padding: 18,
        marginBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
    },
    winnerOfferCard: {
        borderColor: '#facc15',
        borderWidth: 2,
        backgroundColor: '#fefce8',
    },
    offerAvatarPlaceholder: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#e0ecff',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    offerContent: {
        flex: 1,
    },
    offerHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    offerName: {
        fontSize: 17,
        fontWeight: '700',
        color: '#111827',
    },
    offerTagline: {
        marginTop: 4,
        fontSize: 14,
        color: '#6b7280',
    },
    offerPrice: {
        marginTop: 12,
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    offerPriceHidden: {
        marginTop: 12,
        fontSize: 13,
        fontWeight: '600',
        color: '#94a3b8',
    },
    offerRankPill: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        backgroundColor: '#fef3c7',
        borderRadius: 999,
    },
    offerRankText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#b45309',
    },
    emptyOffersBox: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        padding: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyOffersText: {
        marginTop: 12,
        fontSize: 14,
        color: '#475569',
        textAlign: 'center',
    },
    footerWrapper: {
        paddingHorizontal: 24,
        paddingBottom: 32,
    },
    closeButton: {
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        backgroundColor: '#0f766e',
        marginBottom: 12,
    },
    closeButtonDisabled: {
        backgroundColor: '#94a3b8',
    },
    closeButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '700',
    },
    closeButtonTextDisabled: {
        color: '#e2e8f0',
    },
    closeHelperText: {
        marginTop: 6,
        fontSize: 13,
        color: '#f0fdfa',
    },
    cancelButton: {
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: '#ef4444',
        paddingVertical: 14,
        alignItems: 'center',
        backgroundColor: '#fff5f5',
    },
    cancelButtonText: {
        color: '#b91c1c',
        fontSize: 16,
        fontWeight: '700',
    },
    cancelButtonTextDisabled: {
        color: '#fca5a5',
    },
    buttonDisabled: {
        opacity: 0.6,
    },
    helperCaption: {
        marginTop: 12,
        fontSize: 13,
        color: '#64748b',
        textAlign: 'center',
    },
    closedBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 14,
        borderRadius: 14,
        backgroundColor: '#fef3c7',
        borderWidth: 1,
        borderColor: '#f59e0b',
        marginBottom: 16,
    },
    closedBannerText: {
        marginLeft: 10,
        fontSize: 15,
        fontWeight: '600',
        color: '#b45309',
        flex: 1,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        justifyContent: 'flex-start',
    },
    modalContainer: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: 32,
        flex: 1,
        maxHeight: '92%',
        alignSelf: 'stretch',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 20,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderColor: '#e5e7eb',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
    },
    modalCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f3f4f6',
    },
    modalContent: {
        paddingHorizontal: 24,
        paddingVertical: 16,
    },
    modalSection: {
        marginBottom: 16,
    },
    modalLabel: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        color: '#6b7280',
        letterSpacing: 0.6,
        marginBottom: 4,
    },
    modalValue: {
        fontSize: 15,
        lineHeight: 21,
        color: '#1f2937',
    },
    modalEmptyValue: {
        fontSize: 14,
        color: '#9ca3af',
        fontStyle: 'italic',
    },
    attachmentScroller: {
        paddingVertical: 4,
    },
    modalAttachment: {
        width: 120,
        height: 120,
        borderRadius: 12,
        marginRight: 12,
        backgroundColor: '#f3f4f6',
    },
});

export default styles;
