import { StyleSheet } from 'react-native';
import { PALETTE } from '../HomePage/HomePage.styles';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: PALETTE.backgroundLight,
    },
    container: {
        flex: 1,
        backgroundColor: PALETTE.backgroundLight,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: PALETTE.borderSubtle,
        backgroundColor: PALETTE.cardLight,
    },
    headerButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: PALETTE.cardLight,
    },
    headerButtonPlaceholder: {
        width: 40,
        height: 40,
    },
    headerTitle: {
        flex: 1,
        textAlign: 'center',
        fontSize: 18,
        fontWeight: '600',
        color: PALETTE.textPrimary,
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingBottom: 96,
    },
    section: {
        marginTop: 24,
        backgroundColor: PALETTE.cardLight,
        borderRadius: 16,
        padding: 16,
        shadowColor: '#000000',
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 10,
        elevation: 2,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: PALETTE.textPrimary,
    },
    sectionMeta: {
        fontSize: 13,
        color: PALETTE.textSecondary,
    },
    sectionBody: {
        fontSize: 15,
        lineHeight: 22,
        color: PALETTE.textPrimary,
    },
    proposalStatusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: 'rgba(148, 163, 184, 0.18)',
    },
    proposalStatusBadgePending: {
        backgroundColor: 'rgba(59, 130, 246, 0.18)',
    },
    proposalStatusBadgeAccepted: {
        backgroundColor: 'rgba(16, 185, 129, 0.18)',
    },
    proposalStatusBadgeRejected: {
        backgroundColor: 'rgba(239, 68, 68, 0.18)',
    },
    proposalStatusBadgeMuted: {
        backgroundColor: 'rgba(148, 163, 184, 0.18)',
    },
    proposalStatusText: {
        fontSize: 12,
        fontWeight: '600',
        color: PALETTE.textSecondary,
        textTransform: 'uppercase',
    },
    proposalStatusTextPending: {
        color: PALETTE.primary,
    },
    proposalStatusTextAccepted: {
        color: '#059669',
    },
    proposalStatusTextRejected: {
        color: '#DC2626',
    },
    proposalStatusTextMuted: {
        color: '#475569',
    },
    proposalAmount: {
        marginTop: 8,
        fontSize: 18,
        fontWeight: '600',
        color: PALETTE.textPrimary,
    },
    proposalMetaLabel: {
        marginTop: 6,
        fontSize: 13,
        color: PALETTE.textSecondary,
    },
    proposalNotesBlock: {
        marginTop: 12,
        backgroundColor: PALETTE.infoSoft,
        borderRadius: 12,
        padding: 12,
    },
    proposalNotesTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: PALETTE.textPrimary,
        marginBottom: 6,
    },
    proposalNotesText: {
        fontSize: 13,
        lineHeight: 20,
        color: PALETTE.textPrimary,
    },
    attachmentList: {
        paddingVertical: 4,
    },
    attachmentItem: {
        marginRight: 12,
        width: 160,
    },
    attachmentImage: {
        width: '100%',
        height: 120,
        borderRadius: 12,
        backgroundColor: PALETTE.backgroundLight,
    },
    attachmentPlaceholder: {
        width: '100%',
        height: 120,
        borderRadius: 12,
        backgroundColor: PALETTE.backgroundLight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    attachmentPlaceholderText: {
        marginTop: 6,
        fontSize: 12,
        color: PALETTE.textSecondary,
    },
    attachmentCaption: {
        marginTop: 8,
        fontSize: 13,
        color: PALETTE.textPrimary,
    },
    attachmentEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
    },
    attachmentEmptyText: {
        marginTop: 8,
        fontSize: 13,
        color: PALETTE.textSecondary,
        textAlign: 'center',
    },
    previewOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    previewBackdrop: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    },
    previewContent: {
        width: '100%',
        maxWidth: 480,
        maxHeight: '80%',
        backgroundColor: PALETTE.cardLight,
        borderRadius: 18,
        padding: 16,
        alignItems: 'center',
    },
    previewImage: {
        width: '100%',
        height: 320,
        borderRadius: 12,
        backgroundColor: PALETTE.backgroundLight,
    },
    previewCaption: {
        marginTop: 12,
        fontSize: 14,
        color: PALETTE.textPrimary,
        textAlign: 'center',
    },
    previewCloseButton: {
        position: 'absolute',
        top: 12,
        right: 12,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.9)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    footer: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        padding: 16,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderTopWidth: 1,
        borderTopColor: PALETTE.borderSubtle,
    },
    ctaButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: PALETTE.primary,
        paddingVertical: 14,
        borderRadius: 12,
    },
    ctaButtonDisabled: {
        backgroundColor: '#9CA3AF',
    },
    ctaIcon: {
        marginRight: 8,
    },
    ctaText: {
        fontSize: 16,
        fontWeight: '600',
        color: PALETTE.white,
    },
    centerContent: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
    },
    loadingText: {
        marginTop: 16,
        fontSize: 15,
        color: PALETTE.textSecondary,
    },
    errorTitle: {
        marginTop: 12,
        fontSize: 16,
        fontWeight: '600',
        color: PALETTE.textPrimary,
        textAlign: 'center',
    },
    errorSubtitle: {
        marginTop: 8,
        fontSize: 14,
        color: PALETTE.textSecondary,
        textAlign: 'center',
        lineHeight: 20,
    },
});
