import { StyleSheet } from 'react-native';
import { PALETTE } from '../../HomePage/HomePage.styles';

export const TIMELINE_COLORS = {
    done: '#0f766e',
    active: '#2563eb',
    pending: '#cbd5f5',
    canceled: '#ef4444',
    review: '#f59e0b',
};

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: PALETTE.backgroundLight,
    },
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 18,
        paddingBottom: 10,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: PALETTE.borderSubtle,
        shadowColor: '#0f172a',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 1,
    },
    headerTitle: {
        flex: 1,
        marginLeft: 16,
        fontSize: 20,
        fontWeight: '700',
        color: PALETTE.textPrimary,
    },
    headerPlaceholder: {
        width: 40,
        height: 40,
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 32,
    },
    summaryCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 20,
        borderWidth: 1,
        borderColor: PALETTE.borderSubtle,
        shadowColor: '#0f172a',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 3,
        marginBottom: 24,
    },
    summaryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    summaryHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 12,
    },
    summaryIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#e0f2fe',
        marginRight: 14,
    },
    summaryTextBlock: {
        flex: 1,
    },
    summaryTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: PALETTE.textPrimary,
    },
    summarySubtitle: {
        marginTop: 2,
        fontSize: 13,
        color: PALETTE.textSecondary,
    },
    summaryClientRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 18,
    },
    summaryClientAvatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        marginRight: 14,
        backgroundColor: '#e2e8f0',
    },
    summaryClientInfo: {
        flex: 1,
    },
    summaryClientLabel: {
        fontSize: 12,
        color: PALETTE.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    summaryClientName: {
        marginTop: 4,
        fontSize: 16,
        fontWeight: '700',
        color: PALETTE.textPrimary,
    },
    summaryClientPhone: {
        marginTop: 2,
        fontSize: 13,
        color: PALETTE.textSecondary,
    },
    statusBadge: {
        alignSelf: 'flex-start',
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 6,
    },
    statusBadgeText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FFFFFF',
        letterSpacing: 0.4,
    },
    summarySectionLabel: {
        fontSize: 12,
        color: PALETTE.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    summaryDetails: {
        marginTop: 18,
        gap: 16,
    },
    summaryDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    summaryDetailIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#e0f2fe',
        marginRight: 12,
    },
    summaryDetailText: {
        flex: 1,
    },
    summaryDetailLabel: {
        fontSize: 12,
        color: PALETTE.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    summaryDetailValue: {
        marginTop: 4,
        fontSize: 16,
        fontWeight: '600',
        color: PALETTE.textPrimary,
        lineHeight: 22,
    },
    summaryLocationCard: {
        marginTop: 20,
        padding: 16,
        borderRadius: 18,
        backgroundColor: '#f1f5f9',
        borderWidth: 1,
        borderColor: PALETTE.borderSubtle,
    },
    summaryLocationRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    summaryLocationIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#e0f2fe',
        marginRight: 12,
    },
    summaryLocationValue: {
        fontSize: 14,
        color: PALETTE.textPrimary,
        fontWeight: '600',
        lineHeight: 20,
    },
    summaryHint: {
        marginTop: 12,
        fontSize: 12,
        color: PALETTE.textSecondary,
        lineHeight: 18,
    },
    divider: {
        height: 1,
        backgroundColor: PALETTE.borderSubtle,
        marginVertical: 18,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: PALETTE.textPrimary,
        marginBottom: 12,
    },
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 20,
        borderWidth: 1,
        borderColor: PALETTE.borderSubtle,
        marginBottom: 24,
        shadowColor: '#0f172a',
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 2,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    infoIcon: {
        marginRight: 12,
        marginTop: 2,
        color: '#2563eb',
    },
    infoLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: PALETTE.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    infoValue: {
        fontSize: 14,
        color: PALETTE.textPrimary,
        marginTop: 4,
        lineHeight: 20,
    },
    infoHint: {
        fontSize: 12,
        color: PALETTE.textSecondary,
        marginTop: 6,
    },
    attachmentList: {
        marginTop: 10,
        flexDirection: 'row',
    },
    attachmentImage: {
        width: 110,
        height: 110,
        borderRadius: 16,
        marginRight: 12,
        backgroundColor: '#e2e8f0',
    },
    timelineSection: {
        marginTop: 4,
    },
    timelineItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingBottom: 24,
    },
    timelineItemLast: {
        paddingBottom: 0,
    },
    timelineMarkerWrapper: {
        width: 28,
        alignItems: 'center',
        alignSelf: 'stretch',
        flexDirection: 'column',
    },
    timelineConnector: {
        width: 2,
        flex: 1,
        alignSelf: 'center',
        borderRadius: 1,
        backgroundColor: '#dbeafe',
    },
    timelineBullet: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 2,
        borderColor: '#dbeafe',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    timelineBulletInner: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    timelineContent: {
        flex: 1,
        marginLeft: 16,
    },
    timelineLabel: {
        fontSize: 15,
        fontWeight: '700',
        color: PALETTE.textPrimary,
    },
    timelineTimestamp: {
        fontSize: 12,
        color: PALETTE.textSecondary,
        marginTop: 2,
    },
    timelineDescription: {
        fontSize: 13,
        color: '#1f2937',
        marginTop: 6,
        lineHeight: 20,
    },
    reviewStarsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
    },
    reviewStar: {
        marginRight: 4,
    },
    reviewComment: {
        marginTop: 8,
        fontSize: 13,
        lineHeight: 20,
        color: '#1f2937',
        fontStyle: 'italic',
    },
    reviewScore: {
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '600',
        color: '#0f172a',
    },
    timelineActionButton: {
        marginTop: 14,
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 14,
        backgroundColor: '#2563eb',
    },
    timelineActionButtonSecondary: {
        backgroundColor: '#0f766e',
    },
    timelineActionButtonTertiary: {
        backgroundColor: '#428254ff',
    },
    timelineActionButtonDisabled: {
        backgroundColor: '#cbd5f5',
    },
    timelineActionIcon: {
        marginRight: 8,
        color: '#FFFFFF',
    },
    timelineActionLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    timelineActionSpinner: {
        marginRight: 8,
    },
    actionSection: {
        marginTop: 4,
    },
    actionButtons: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        rowGap: 12,
        columnGap: 12,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 14,
        backgroundColor: '#2563eb',
    },
    actionButtonSecondary: {
        backgroundColor: '#0f766e',
    },
    actionButtonTertiary: {
        backgroundColor: '#0ea5e9',
    },
    actionButtonDisabled: {
        backgroundColor: '#cbd5f5',
    },
    actionIcon: {
        marginRight: 8,
        color: '#FFFFFF',
    },
    actionLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    actionSpinner: {
        marginRight: 8,
    },
    helperText: {
        marginTop: 12,
        fontSize: 12,
        color: PALETTE.textSecondary,
    },
    alertBanner: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: 14,
        borderRadius: 16,
        backgroundColor: '#fef3c7',
        borderWidth: 1,
        borderColor: '#facc15',
        marginTop: 10,
    },
    alertIcon: {
        marginRight: 8,
        color: '#b45309',
        marginTop: 2,
    },
    alertText: {
        flex: 1,
        fontSize: 13,
        color: '#92400e',
        lineHeight: 20,
    },
    emptyState: {
        paddingVertical: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyStateText: {
        marginTop: 12,
        fontSize: 14,
        color: PALETTE.textSecondary,
        textAlign: 'center',
    },
    refreshIndicator: {
        marginLeft: 12,
    },
});
