"""upgrade

Revision ID: 02ac877155d9
Revises: 20251026_1618
Create Date: 2025-11-13 21:42:58.379325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02ac877155d9'
down_revision = '20251026_1618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Aplicar los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_licenses', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('services', sa.Column('currency', sa.String(length=3), nullable=True))
    op.create_foreign_key(None, 'services', 'currencies', ['currency'], ['code'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'currency')
    op.alter_column('provider_licenses', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###