"""upgrade

Revision ID: a996d6c74345
Revises: fcbf7d08cef7
Create Date: 2025-10-22 18:18:05.898251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a996d6c74345'
down_revision = 'fcbf7d08cef7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Aplicar los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###