"""fix push token

Revision ID: 0d09cbd6e34d
Revises: 2c9e21dfa48a
Create Date: 2025-11-24 17:05:37.544529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d09cbd6e34d'
down_revision = '2c9e21dfa48a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Aplicar los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###