"""descripcion

Revision ID: 40de939290a1
Revises: 62389b397317
Create Date: 2025-10-08 18:01:04.980448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40de939290a1'
down_revision = '62389b397317'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Aplicar los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###