"""add_rehire_columns_to_service_requests

Revision ID: b43a261710e5
Revises: a808f46d6d01
Create Date: 2025-12-11 19:18:24.048966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43a261710e5'
down_revision = 'a808f46d6d01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Aplicar los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('parent_service_id', sa.BigInteger(), nullable=True))
    op.add_column('service_requests', sa.Column('target_provider_profile_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_service_requests_target_provider', 'service_requests', ['target_provider_profile_id'], unique=False)
    op.create_foreign_key(None, 'service_requests', 'services', ['parent_service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'service_requests', 'provider_profiles', ['target_provider_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.drop_index('ix_service_requests_target_provider', table_name='service_requests')
    op.drop_column('service_requests', 'target_provider_profile_id')
    op.drop_column('service_requests', 'parent_service_id')
    # ### end Alembic commands ###