"""actualizo db provedor y agrego licencias

Revision ID: 62389b397317
Revises: d32867b6f0f1
Create Date: 2025-10-06 17:00:20.721329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62389b397317'
down_revision = 'd32867b6f0f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Aplicar los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_licenses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('license_number', sa.String(length=120), nullable=False),
    sa.Column('license_type', sa.String(length=120), nullable=True),
    sa.Column('issued_by', sa.String(length=120), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['provider_profile_id'], ['provider_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_licenses_id'), 'provider_licenses', ['id'], unique=False)
    op.add_column('provider_profiles', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.alter_column('provider_profiles', 'rating_avg',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               nullable=False)
    op.alter_column('provider_profiles', 'total_reviews',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('provider_profiles', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_column('provider_profiles', 'is_online')
    op.drop_column('provider_profiles', 'service_radius_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir los cambios de la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('service_radius_km', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('provider_profiles', sa.Column('is_online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('provider_profiles', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('provider_profiles', 'total_reviews',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('provider_profiles', 'rating_avg',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               nullable=True)
    op.drop_column('provider_profiles', 'updated_at')
    op.drop_index(op.f('ix_provider_licenses_id'), table_name='provider_licenses')
    op.drop_table('provider_licenses')
    # ### end Alembic commands ###