import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 1,
  },
  iconButton: {
    padding: 4,
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  helperText: {
    color: '#6B7280',
    fontSize: 13,
    lineHeight: 18,
  },
  formGroup: {
    marginTop: 24,
  },
  label: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 8,
  },
  toggleGroup: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    padding: 4,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleButtonSpacing: {
    marginRight: 6,
  },
  toggleButtonActive: {
    backgroundColor: '#2563EB',
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  toggleButtonTextActive: {
    color: '#FFFFFF',
  },
  requestTypeHelper: {
    marginTop: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    padding: 12,
  },
  requestTypeHelperText: {
    color: '#4B5563',
    fontSize: 13,
    lineHeight: 18,
  },
  noticeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: 10,
    padding: 12,
    marginTop: 16,
  },
  noticeIcon: {
    marginRight: 10,
  },
  noticeText: {
    flex: 1,
    color: '#1D4ED8',
    fontSize: 13,
    lineHeight: 18,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    backgroundColor: '#FFFFFF',
    color: '#111827',
  },
  multilineInput: {
    minHeight: 140,
  },
  inlineSpinner: {
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressErrorBox: {
    padding: 16,
    borderRadius: 10,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    alignItems: 'center',
  },
  errorText: {
    color: '#B91C1C',
    fontSize: 14,
    textAlign: 'center',
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#2563EB',
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    marginLeft: 6,
  },
  addressEmptyBox: {
    padding: 20,
    borderRadius: 12,
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
  },
  addressEmptyText: {
    color: '#4B5563',
    textAlign: 'center',
    fontSize: 14,
  },
  addAddressButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#2563EB',
  },
  addAddressButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    marginLeft: 8,
  },
  addressList: {
    marginTop: 4,
  },
  addressCard: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
  },
  addressCardSelected: {
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
  },
  addressCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addressTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
  },
  addressBadge: {
    fontSize: 12,
    color: '#1F2937',
    backgroundColor: '#E0E7FF',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  addressSubtitle: {
    color: '#4B5563',
    fontSize: 13,
  },
  selectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  selectedBadgeText: {
    color: '#2563EB',
    fontWeight: '600',
    fontSize: 13,
    marginLeft: 6,
  },
  attachmentEmptyBox: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    marginBottom: 12,
  },
  attachmentEmptyText: {
    color: '#4B5563',
    textAlign: 'center',
    fontSize: 14,
  },
  attachmentCard: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
  },
  attachmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  attachmentTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
  },
  attachmentContent: {
    marginBottom: 12,
  },
  attachmentPreviewWrapper: {
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    height: 180,
    marginBottom: 12,
  },
  attachmentPreview: {
    width: '100%',
    height: '100%',
  },
  attachmentOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(17, 24, 39, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachmentOverlayText: {
    color: '#FFFFFF',
    fontSize: 12,
    marginTop: 6,
  },
  attachmentErrorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  attachmentErrorText: {
    flex: 1,
    color: '#B91C1C',
    fontSize: 12,
    marginHorizontal: 6,
  },
  retryButtonInline: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2563EB',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  retryButtonInlineText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  attachmentStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  attachmentStatusText: {
    color: '#16A34A',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 6,
  },
  addAttachmentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  addAttachmentButtonText: {
    color: '#2563EB',
    fontWeight: '600',
    marginLeft: 8,
  },
  submitButton: {
    marginTop: 32,
    marginBottom: 40,
    backgroundColor: '#2563EB',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  submitButtonDisabled: {
    backgroundColor: '#93C5FD',
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
});