import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f1f5f9',
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 40,
    },
    header: {
        marginTop: 16,
        paddingHorizontal: 20,
        paddingBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    headerTitleWrapper: {
        flex: 1,
        marginLeft: 16,
    },
    headerTitle: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1.1,
        color: '#0284c7',
        textTransform: 'uppercase',
    },
    headerSubtitle: {
        marginTop: 4,
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    infoButton: {
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#e0f2fe',
        borderRadius: 999,
    },
    infoButtonText: {
        marginLeft: 6,
        fontSize: 13,
        fontWeight: '600',
        color: '#0369a1',
    },
    statusCard: {
        marginHorizontal: 20,
        marginTop: 12,
        borderRadius: 20,
        backgroundColor: '#ffffff',
        padding: 18,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 3,
    },
    statusTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: '#e0f2fe',
    },
    statusBadgeIcon: {
        marginRight: 6,
    },
    statusBadgeText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#0f172a',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    countdownWrapper: {
        alignItems: 'flex-end',
    },
    countdownValue: {
        fontSize: 30,
        fontWeight: '800',
        color: '#0f172a',
        letterSpacing: 1,
    },
    countdownValueExpired: {
        color: '#94a3b8',
    },
    countdownCaption: {
        marginTop: 2,
        fontSize: 12,
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    statusBodyRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    brandMark: {
        width: 48,
        height: 48,
        marginRight: 14,
    },
    statusHeaderCopy: {
        flex: 1,
    },
    statusTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: '#0f172a',
    },
    statusDescription: {
        marginTop: 6,
        fontSize: 13,
        lineHeight: 19,
        color: '#475569',
    },
    statusHint: {
        marginTop: 12,
        fontSize: 12,
        color: '#64748b',
        lineHeight: 18,
    },
    offersSection: {
        marginHorizontal: 20,
        marginTop: 18,
        padding: 20,
        borderRadius: 24,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dbeafe',
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 3,
    },
    offersHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 18,
    },
    offersHeaderCopy: {
        flex: 1,
        paddingRight: 12,
    },
    offersTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    offersSubtitle: {
        marginTop: 4,
        fontSize: 13,
        color: '#475569',
        lineHeight: 18,
    },
    offersBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#e0f2fe',
        borderWidth: 1,
        borderColor: '#bfdbfe',
    },
    offersBadgeText: {
        marginLeft: 6,
        fontSize: 13,
        fontWeight: '700',
        color: '#0369a1',
    },
    offersList: {
        marginTop: 4,
    },
    offerItemWrapper: {
        marginBottom: 12,
    },
    proposalCard: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#dbeafe',
        backgroundColor: '#f8fbff',
        padding: 16,
    },
    proposalCardDisabled: {
        borderColor: '#d1fae5',
        backgroundColor: '#ecfdf5',
    },
    proposalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    proposalProvider: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0f172a',
        flexShrink: 1,
        paddingRight: 8,
    },
    proposalPrice: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0f172a',
    },
    proposalMetaRow: {
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    proposalMetaIcon: {
        marginRight: 8,
    },
    proposalMetaText: {
        fontSize: 13,
        color: '#475569',
        flex: 1,
        lineHeight: 18,
    },
    proposalMetaTextMuted: {
        color: '#94a3b8',
    },
    proposalNotes: {
        marginTop: 10,
        fontSize: 13,
        color: '#1f2937',
        lineHeight: 18,
    },
    proposalFooterRow: {
        marginTop: 16,
    },
    proposalPrimaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#0f766e',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        alignSelf: 'stretch',
    },
    proposalPrimaryButtonDisabled: {
        backgroundColor: '#d1fae5',
    },
    proposalPrimaryIcon: {
        marginRight: 8,
    },
    proposalPrimaryButtonText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#ecfeff',
    },
    proposalPrimaryButtonTextDisabled: {
        color: '#0f766e',
    },
    offersFooterHint: {
        marginHorizontal: 20,
        marginTop: 8,
        alignItems: 'center',
        paddingBottom: 12,
    },
    footerWrapper: {
        paddingHorizontal: 24,
        paddingBottom: 32,
        marginTop: 24,
    },
    cancelButton: {
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: '#ef4444',
        paddingVertical: 14,
        alignItems: 'center',
        backgroundColor: '#fff5f5',
        marginBottom: 12,
    },
    cancelButtonText: {
        color: '#b91c1c',
        fontSize: 16,
        fontWeight: '700',
    },
    cancelButtonTextDisabled: {
        color: '#fca5a5',
    },
    buttonDisabled: {
        opacity: 0.6,
    },
    switchButton: {
        backgroundColor: '#0f766e',
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
    },
    switchButtonDisabled: {
        backgroundColor: '#94a3b8',
    },
    switchButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    switchButtonTextDisabled: {
        color: '#e2e8f0',
    },
    switchHelperText: {
        marginTop: 6,
        fontSize: 13,
        color: '#e2e8f0',
    },
    switchHelperTextReady: {
        color: '#f0fdfa',
    },
    emptyOffersWrapper: {
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 180,
    },
    emptyOffersText: {
        fontSize: 14,
        lineHeight: 20,
        textAlign: 'center',
        color: '#475569',
        marginTop: 12,
    },
    refreshHint: {
        fontSize: 12,
        color: '#94a3b8',
    },
    serviceConfirmedBanner: {
        marginHorizontal: 20,
        marginBottom: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderRadius: 12,
        backgroundColor: '#d1fae5',
        flexDirection: 'row',
        alignItems: 'center',
    },
    serviceConfirmedIcon: {
        marginRight: 8,
    },
    serviceConfirmedText: {
        flex: 1,
        fontSize: 13,
        lineHeight: 18,
        color: '#115e59',
    },
    requestInfoCard: {
        marginHorizontal: 20,
        marginTop: 16,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    requestInfoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    requestInfoTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: '#0f172a',
    },
    requestName: {
        marginTop: 10,
        fontSize: 15,
        fontWeight: '600',
        color: '#0f172a',
    },
    requestInfoDescription: {
        marginTop: 8,
        fontSize: 14,
        lineHeight: 20,
        color: '#1f2937',
    },
    requestInfoMetaRow: {
        marginTop: 12,
        flexDirection: 'row',
        alignItems: 'center',
    },
    requestInfoMetaIcon: {
        marginRight: 8,
    },
    requestInfoMetaText: {
        flex: 1,
        fontSize: 13,
        color: '#0369a1',
    },
    attachmentsScroll: {
        paddingVertical: 8,
    },
    attachmentImage: {
        width: 120,
        height: 120,
        borderRadius: 12,
        marginRight: 12,
        backgroundColor: '#e2e8f0',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        justifyContent: 'flex-start',
    },
    modalContainer: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: 32,
        flex: 1,
        maxHeight: '92%',
        alignSelf: 'stretch',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 20,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderColor: '#e5e7eb',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
    },
    modalCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f3f4f6',
    },
    modalContent: {
        paddingHorizontal: 24,
        paddingVertical: 16,
        paddingBottom: 40,
    },
    modalSection: {
        marginBottom: 18,
    },
    modalLabel: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        color: '#6b7280',
        letterSpacing: 0.6,
        marginBottom: 4,
    },
    modalValue: {
        fontSize: 15,
        lineHeight: 21,
        color: '#1f2937',
    },
    modalHelper: {
        marginTop: 4,
        fontSize: 12,
        color: '#64748b',
    },
    modalProviderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalProviderAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginRight: 16,
    },
    modalProviderAvatarFallback: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#e2e8f0',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    modalProviderInfo: {
        flex: 1,
    },
    modalProviderName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    modalProviderMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        flexWrap: 'wrap',
    },
    modalChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fef3c7',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 4,
        marginRight: 8,
        marginBottom: 6,
    },
    modalChipText: {
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '600',
        color: '#92400e',
    },
    modalChipSecondary: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e0f2fe',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 4,
        marginRight: 8,
        marginBottom: 6,
    },
    modalChipSecondaryText: {
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '600',
        color: '#0f172a',
    },
    modalChipMuted: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e2e8f0',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 4,
        marginRight: 8,
        marginBottom: 6,
    },
    modalChipMutedText: {
        marginLeft: 4,
        fontSize: 12,
        color: '#475569',
    },
    modalNotesBox: {
        marginTop: 4,
        backgroundColor: '#f8fafc',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        padding: 16,
    },
    modalNotesLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#0f172a',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 6,
    },
    modalNotesText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#1f2937',
    },
    modalEmptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 32,
    },
    modalEmptyStateText: {
        marginTop: 12,
        fontSize: 14,
        color: '#64748b',
        textAlign: 'center',
        lineHeight: 20,
    },
});

export default styles;
