import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        marginTop: 16,
        paddingHorizontal: 20,
        paddingTop: 8,
        paddingBottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    infoButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: '#e0f2fe',
        borderRadius: 16,
    },
    infoButtonText: {
        marginLeft: 6,
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
    },
    statusWrapper: {
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 16,
        alignItems: 'center',
    },
    brandLogo: {
        width: 96,
        height: 96,
        marginBottom: 12,
    },
    statusTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 12,
    },
    countdown: {
        fontSize: 54,
        fontWeight: '700',
        color: '#111827',
        letterSpacing: 4,
    },
    statusSubtitle: {
        marginTop: 12,
        fontSize: 15,
        color: '#6b7280',
        textAlign: 'center',
    },
    listContent: {
        paddingHorizontal: 18,
        paddingBottom: 24,
        paddingTop: 4,
    },
    listContentEmpty: {
        flexGrow: 1,
        justifyContent: 'center',
    },
    offerCard: {
        backgroundColor: '#f0f5f2',
        borderRadius: 18,
        padding: 18,
        marginBottom: 16,
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    offerAvatar: {
        width: 52,
        height: 52,
        borderRadius: 26,
        marginRight: 16,
    },
    offerAvatarFallback: {
        width: 52,
        height: 52,
        borderRadius: 26,
        marginRight: 16,
        backgroundColor: '#e2e8f0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    offerContent: {
        flex: 1,
    },
    offerName: {
        fontSize: 17,
        fontWeight: '700',
        color: '#111827',
    },
    offerTagline: {
        marginTop: 6,
        fontSize: 13,
        color: '#4b5563',
    },
    offerMetaRow: {
        marginTop: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    offerPrice: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    offerRating: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    offerRatingText: {
        marginLeft: 6,
        fontSize: 15,
        fontWeight: '600',
        color: '#0f172a',
    },
    offerRatingReviews: {
        marginLeft: 2,
        fontSize: 13,
        color: '#475569',
    },
    offerNoRating: {
        fontSize: 13,
        color: '#64748b',
        fontStyle: 'italic',
    },
    acceptButton: {
        marginLeft: 16,
        backgroundColor: '#e57355',
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 18,
    },
    acceptButtonDisabled: {
        backgroundColor: '#cbd5f5',
    },
    acceptButtonText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 16,
    },
    acceptButtonTextDisabled: {
        color: '#1f2937',
    },
    footerWrapper: {
        paddingHorizontal: 24,
        paddingBottom: 32,
    },
    cancelButton: {
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: '#ef4444',
        paddingVertical: 14,
        alignItems: 'center',
        backgroundColor: '#fff5f5',
        marginBottom: 12,
    },
    cancelButtonText: {
        color: '#b91c1c',
        fontSize: 16,
        fontWeight: '700',
    },
    cancelButtonTextDisabled: {
        color: '#fca5a5',
    },
    buttonDisabled: {
        opacity: 0.6,
    },
    switchButton: {
        backgroundColor: '#0f766e',
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
    },
    switchButtonDisabled: {
        backgroundColor: '#94a3b8',
    },
    switchButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    switchButtonTextDisabled: {
        color: '#e2e8f0',
    },
    switchHelperText: {
        marginTop: 6,
        fontSize: 13,
        color: '#e2e8f0',
    },
    switchHelperTextReady: {
        color: '#f0fdfa',
    },
    emptyOffersWrapper: {
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 180,
    },
    emptyOffersText: {
        fontSize: 14,
        lineHeight: 20,
        textAlign: 'center',
        color: '#475569',
        marginTop: 12,
    },
    listFooterHint: {
        alignItems: 'center',
        paddingVertical: 12,
    },
    refreshHint: {
        fontSize: 12,
        color: '#94a3b8',
    },
    serviceConfirmedBanner: {
        marginHorizontal: 20,
        marginBottom: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderRadius: 12,
        backgroundColor: '#d1fae5',
        flexDirection: 'row',
        alignItems: 'center',
    },
    serviceConfirmedIcon: {
        marginRight: 8,
    },
    serviceConfirmedText: {
        flex: 1,
        fontSize: 13,
        lineHeight: 18,
        color: '#115e59',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        justifyContent: 'flex-start',
    },
    modalContainer: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: 32,
        flex: 1,
        maxHeight: '92%',
        alignSelf: 'stretch',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 20,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderColor: '#e5e7eb',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
    },
    modalCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f3f4f6',
    },
    modalContent: {
        paddingHorizontal: 24,
        paddingVertical: 16,
    },
    modalSection: {
        marginBottom: 16,
    },
    modalLabel: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        color: '#6b7280',
        letterSpacing: 0.6,
        marginBottom: 4,
    },
    modalValue: {
        fontSize: 15,
        lineHeight: 21,
        color: '#1f2937',
    },
    modalEmptyValue: {
        fontSize: 14,
        color: '#9ca3af',
        fontStyle: 'italic',
    },
    attachmentScroller: {
        paddingVertical: 4,
    },
    modalAttachment: {
        width: 120,
        height: 120,
        borderRadius: 12,
        marginRight: 12,
        backgroundColor: '#f3f4f6',
    },
});

export default styles;
